import React from "react";
import Head from "next/head";
import "./sass/style.scss";

import { Inter } from "next/font/google";

import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Strona Główna",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="pl">
			<head>
				<meta charset="UTF-8" />
				<meta http-equiv="X-UA-Compatible" content="IE=edge" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />

				<meta name="author" content="Kurpiowski Bartnik" />
				<meta name="keywords" content="TAGI" />

				<script
					src="https://kit.fontawesome.com/1fcccd6048.js"
					crossorigin="anonymous"
				></script>
			</head>

			<body className={inter.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
