
import Slider from "../components/slider";
import HowTo from "../components/how-to";
import Description from "../components/description";
import Register from "../components/register";
import Recomended from "../components/recomended.js";
import ArticlesBar from "../components/articles-bar";


// export const metadata = {
// 	title: "Strona Główna",
// 	description: "Generated by create next app",
// 	keywords: "TAGI",
// };

export default function Home() {
	return (
		<main className="main home">
			<div className="main-wrapper">
				<Slider />
				<HowTo />
				<Description />
				<Register />
				<Recomended />
				<ArticlesBar />
			</div>
		</main>
	);
}
