

import Image from "next/image";

import Slider from "../components/slider";
import HowTo from "../components/how-to";
import Description from "../components/description";
import Register from "../components/register";
import Favourites from "../components/favourites";
import Articles from "../components/articles-bar";

// export const metadata = {
// 	title: "Strona Główna",
// 	description: "Generated by create next app",
// 	keywords: "TAGI",
// };

export default function Home() {
	return (
		<main className="main home">
			<Slider />
			<HowTo />
			<Description />
			<Register />
			<Favourites />
			<ArticlesBar />
		</main>
	);
}
